### PR TITLE
Fix next.config.js with es2015 babel preset

### PR DESCRIPTION
**Pull request by fsegouin**
I think the current example is borked, I had to add a `.babelrc` file with the es2015 preset to fix the spread operator in `next.config.js` not being supported oob. Let me know if there is another way of doing this 👍

### CODE REVIEW

**Comment by elmasse** [comment]
@fsegouin Thanks for taking the time for submitting a PR.

I'll check it out later today, but I believe es2015 preset is part of the `next/babel` configuration. I'll give it a try again with next 4.1.x in case that has been changed.

I was able to run this example with no other changes locally, at least with next 4.0.x and react 16.

What steps did you follow to get the examples running?

Thanks again!
Max

**Comment by fsegouin** [comment]
You're more than welcome! Thanks again for your work on nextein.

I cloned this repo and followed the instructions, as simple as that.

You're right with es2015 being part of the `next/babel` config but so far I haven't been able to use ES6 syntax in the `next.config.js` file as it's not being picked up by the babel config. I used a workaround discussed here https://github.com/zeit/next.js/issues/2916.

**Comment by elmasse** [comment]
Oh, I think I know what's going on.
What node version are you using? I have 8.7 installed and 8.x  supports object spread natively. That's why it works fine for me. 

It is true that next.config.js is not picked up by babel. I almost forgot about that!

Not sure if It might be worthy to support older versions of node since nextein is still in beta and node 8 LTS is around the corner (10/31).

**Comment by fsegouin** [comment]
Uh good call! I use node v7.9.0, I just updated to v8.7.0 and it's working without issues.

Might be worth adding that as a note on the README 😉

**Pull request closed without merging**
